export const FTL_NEWS = "FTL_NEWS";
export const TOGGLE_IS_ERROR = "TOGGLE_IS_ERROR";
export const TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING";
export const ADD_REQUEST_TRANSPORTATION = "ADD_REQUEST_TRANSPORTATION";
export const DATES_SORT_SAGA = "DATES_SORT_SAGA";
